version: "3"
services:
  postgres:
    image: postgis/postgis:11-2.5
    env_file:
      - .env
    environment:
      - PGPORT=${POSTGRES_PORT:-5432}
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:5.0-alpine
    volumes:
      - redis:/data

  convertit:
    image: makinacorpus/convertit:latest

  screamshotter:
    image: makinacorpus/screamshotter:v2

  celery:
    image: geotrek
    build:
      context: .
    env_file:
      - .env
    volumes:
        - .:/opt/geotrek-admin
    depends_on:
      - postgres
      - redis
    user: ${UID:-1000}:${GID:-1000}
    command: celery -A geotrek worker -c 1

  web:
    image: geotrek
    env_file:
      - .env
    ports:
      - "${WEB_PORT:-8000}:8000"
    volumes:
      - ./:/opt/geotrek-admin/
      - ../../django/django-mapentity:/opt/venv/src/mapentity
    depends_on:
      - postgres
      - redis
      - screamshotter
      - convertit
    user: ${UID:-1000}:${GID:-1000}
    command: ./manage.py runserver 0.0.0.0:8000
    networks:
      default:
        aliases:
          - ${SERVER_NAME}

volumes:
  postgres:
  redis:
